project_name: fpm-metrics-adapter
version: 2

builds:
  - id: skpr-fpm-metrics-adapter
    main: cmd/skpr-fpm-metrics-adapter/main.go
    binary: skpr-fpm-metrics-adapter
    ldflags:
      - -extldflags '-static' -s -w
    env:
      - CGO_ENABLED=0
    goos: [ linux ]
    goarch: [ amd64, arm64 ]
  - id: skpr-fpm-metrics-adapter-sidecar
    main: cmd/skpr-fpm-metrics-adapter-sidecar/main.go
    binary: skpr-fpm-metrics-adapter-sidecar
    ldflags:
      - -extldflags '-static' -s -w
    env:
      - CGO_ENABLED=0
    goos: [ linux ]
    goarch: [ amd64, arm64 ]

archives:
  - ids:
    - none

checksum:
  disable: true

dockers_v2:
  - id: skpr-fpm-metrics-adapter
    dockerfile: dockerfiles/metrics-adapter/Dockerfile
    ids:
      - skpr-fpm-metrics-adapter
    images:
      - "ghcr.io/skpr/fpm-metrics-adapter"
    tags:
      - "apiserver-v{{ .Version }}"
      - "apiserver-latest"
  - id: skpr-fpm-metrics-adapter-sidecar
    dockerfile: dockerfiles/sidecar/Dockerfile
    ids:
      - skpr-fpm-metrics-adapter-sidecar
    images:
      - "ghcr.io/skpr/fpm-metrics-adapter"
    tags:
      - "sidecar-v{{ .Version }}"
      - "sidecar-latest"

changelog:
  use: github-native
