[tools]
go = "1.25"
"ubi:golangci/golangci-lint" = "latest"
"ubi:goreleaser/goreleaser" = "latest"

[env]
CGO_ENABLED=0

[tasks.vendor]
description = "Vendor resets the main module's vendor directory to include all packages needed to build the application"
run = "go mod vendor"

[tasks.tidy]
description = "Tidy makes sure go.mod matches the source code in the module"
run = "go mod tidy"

[tasks."build:all"]
description = "Build all the applications"
depends = [
  "build skpr-fpm-metrics-adapter",
  "build skpr-fpm-metrics-adapter-sidecar"
]

[tasks.build]
description = "Build the application"
run = '''
go build -o bin/{{arg(name="app")}} -ldflags=${CLI_LDFLAGS} github.com/skpr/fpm-metrics-adapter/cmd/{{arg(name="app")}}
'''
depends = ["vendor"]

[tasks."lint"]
description = "Linting automatically checks code for errors and style issues"
run = "golangci-lint run"
depends = ["tidy"]

[tasks.test]
description = "Checks to verify code correctness"
run = "go test -cover ./..."
depends = ["vendor"]

[tasks."test:integration"]
description = "Checks to verify code correctness"
run = "go test -cover -tags=integration ./internal/tests"

[tasks."run:sidecar"]
description = "Run the sidecar locally"
run = "./bin/skpr-fpm-metrics-adapter-sidecar --port :8080"
depends = ["build skpr-fpm-metrics-adapter-sidecar"]

[tasks.release]
description = "Release the command line interface"
run = "goreleaser"
depends = ["vendor"]
