name: 📋 Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

jobs:
  lint:
    name: 📋 Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v5

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 Lint
        run: mise lint

  test:
    name: 📋 Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v5

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 Lint
        run: mise test

  integration-test:
    name: 📋 Integration test
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v5

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start FPM
        run: |
          docker compose up --quiet-pull -d

      - name: Test sidecar
        run: | 
          mise build skpr-fpm-metrics-adapter-sidecar
          ./bin/skpr-fpm-metrics-adapter-sidecar --port :8080 &
          # Needed because if request comes too early, server hasn't fetched results
          sleep 2
          mise test:integration
